const icons = {
    logoR: require('../assets/icons/logor.png'),
    logoB: require('../assets/icons/logob.png'),
    arrowD: require('../assets/icons/arrowdown.png'),
    arrowU: require('../assets/icons/arrowup.png'),
    tick: require('../assets/icons/tick.png'),
    close: require('../assets/icons/close.png'),
    healthpro: require("../assets/icons/healthpro.png"),
    hospman: require("../assets/icons/hospman.png"),
    patient: require("../assets/icons/patient.png"),
    patientB: require("../assets/icons/patientB.png"),
    hospmanB: require("../assets/icons/hospmanB.png"),
    healthproB: require("../assets/icons/healthproB.png"),
    next: require("../assets/icons/next.png"),
    back: require("../assets/icons/back.png"),
    upload: require("../assets/icons/upload.png"),
    home: require("../assets/icons/home.png"),
    medfolder: require("../assets/icons/medfolder.png"),
    settings: require("../assets/icons/settings.png"),
    contacts: require("../assets/icons/contacts.png"),
    avatar: require("../assets/icons/avatar.png"),
    notifR: require("../assets/icons/notifR.png"),
    car: require("../assets/icons/car.png"),
    watch: require("../assets/icons/watch.png"),
    CGM: require("../assets/icons/CGM.png"),
    ECG: require("../assets/icons/ECG.png"),
    blood: require("../assets/icons/blood.png"),
    loupe: require("../assets/icons/loupe.png"),
};

export default icons